We need to autoreconf, because of flat namespace issues.
Building this in maintainer mode leads to errors:

Error: /sw/src/fink.build/root-ledger26-shlibs-2.6.3-1/sw/lib/libledger-2.6.3.dylib appears to have been linked using a flat namespace.
       If this package BuildDepends on libtool2, make sure that you use
          BuildDepends: libtool2 (>= 2.4.2-4).
       and use autoreconf to regenerate the configure script.
       If the package doesn't BuildDepend on libtool2, you'll need to
       update its build procedure to avoid passing
          -Wl,-flat_namespace
       when linking libraries.